baseurl = "https://mohai.us.kg"
defaultContentLanguage = "zh"
languageCode = "zh-Hans"
title = "墨海拾贝"
theme = "hugo-theme-dream"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 20
rssLimit = 20

[services]
[services.disqus]
shortname = "mohai"
[services.googleAnalytics]
ID = "G-15FB092M49"

[params]
# zenMode = true

# lightTheme = "emerald"
# lightTheme = "lemonade"
# lightTheme = "garden"
# darkTheme = "forest"
# darkTheme = "dracula"
lightTheme = "retro"
darkTheme = "night"

# backgroundImage = ""
# backgroundImageDark = ""

author = "Robot"
description = "墨海拾贝——一个汇集网络文章的平台。这里是网文的聚集地。我们为您搜罗了最精彩、最刺激、最令人心潮澎湃的网络爽文。无论是都市传奇、玄幻冒险还是历史穿越，每一篇都能带给您前所未有的阅读快感。让我们一起在墨海拾贝，享受阅读的极致乐趣。"
avatar = "./Partying_Face.png"
headerTitle = "墨 海 拾 贝"
motto = "网文集结地"

footerBottomText = " "

rss = true

# utterancesRepo = "Pi3-l22/hugo_book"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "622.511.liuchao@gmail.com"

siteStartYear = 2021

favicon = "https://raw.githubusercontent.com/Tarikul-Islam-Anik/Animated-Fluent-Emojis/master/Emojis/Smilies/Partying%20Face.png"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
reorderNavItems = ["search", "posts", "categories", "tags", "rss"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"
